[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rps_game = "B7w4FD8f6geF7TfKzeVb48NtNWXjiWWCqWayPd4N69DJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
rps_game = "YourProgramIDHere"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
