[package]
name = "rps-game"
version = "0.1.0"
description = "Rock Paper Scissors on Solana"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = "0.28.0"
solana-program = "1.14.11"

[features]
no-entrypoint = []